### ISSUE TITLE
ST3 3065 duplicate icons

### ISSUE THREAD

**Issue by clavearnel** [MarkHMorrison/nexus-theme#15]
I update the ST3 to 3065 but theres a duplicate folder icons....

![image](https://cloud.githubusercontent.com/assets/4475797/4113381/ccd73752-324b-11e4-8042-82ee9e0296da.png)

**Comment by jpblancoder** [comment]
Same duplicate folder icons for me. They are hard to see, since the icons are black and the background is also black. Also, the developer added various file icons (depending on file extension), which are not displayed when using Nexus.

This would help anyone that wants to do some theme file editing themselves:
http://www.reddit.com/r/SublimeText/comments/2ewbj5/sublime_text_3_beta_build_3065_released/

**Comment by MarcelRobitaille** [comment]
Just came to report it. Thanks clavearnel.

**Comment by txtsd** [comment]
Can we get an option to use either the themes icons or the defaults ones? Just not both at the same time.

**Comment by shanecav** [comment]
I have the same issue.

**Comment by lianghu** [comment]
please update the theme as here:

http://www.sublimetext.com/forum/viewtopic.php?f=2&t=16719&start=20#p62992
